name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Update Homebrew
        run: brew update
      - name: Install shellcheck
        run: brew install shellcheck
      - name: Run shell check
        run: shellcheck mac -e SC2039
      - name: Create symlink for .laptop.local
        run: ln -s "$(pwd)/.laptop.local" "$HOME/.laptop.local"
      - name: Run laptop setup script
        run: sh mac
